In [ ]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
from pprint import pprint
import time
import pymysql
from configparser import ConfigParser

In [2]:
import sys
!{sys.executable} -m pip install requests beautifulsoup4 pandas

Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: beautifulsoup4 in .\.venv\Lib\site-packages (4.14.3)
Collecting pandas
  Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Using cached charset_normalizer-3.4.7-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.15-py3-none-any.whl.metadata (7.7 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: soupsieve>=1.6.1 in .\.venv\Lib\site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in .\.venv\Lib\site-packages (from beautifulsoup4) (4.15.0)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached charset_normalizer-3.4.7-cp312-cp312-win_amd64.whl (159 kB)
Using cached idna-3.15-py3-none-any.whl (72 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
Downloading certifi-2026.5.20-py3-none-any.whl (134 kB)
Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl (12.3 MB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: urllib3, tzdata, numpy, idna, charset_normalizer, certifi, requests, pandas

   ---------------------------------------- 0/8 [urllib3]
   ----- ---------------------------------- 1/8 [tzdata]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   ---------- ----------------------------- 2/8 [numpy]
   --------------- ------------------------ 3/8 [idna]
   -------------------- ------------------- 4/8 [charset_normalizer]
   ------------------------------ --------- 6/8 [requests]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ----------------------------------- ---- 7/8 [pandas]
   ---------------------------------------- 8/8 [pandas]

Successfully installed certifi-2026.5.20 charset_normalizer-3.4.7 idna-3.15 numpy-2.4.6 pandas-3.0.3 requests-2.34.2 tzdata-2026.2 urllib3-2.7.0

In [2]:
%pip install requests pandas time  pymysql configparser

Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting pandas
  Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement time (from versions: none)
ERROR: No matching distribution found for time

In [8]:
%pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp312-cp312-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.0 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 21.7 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1
Note: you may need to restart the kernel to use updated packages.

In [31]:
url = "http://export.arxiv.org/api/query?search_query=cat:cs.CV&max_results=2"

res = requests.get(url)

print(f"狀態碼： {res.status_code}")

print(res.text[:2000])
print(f"型別：{type(res.text)}")

狀態碼： 200
<?xml version='1.0' encoding='UTF-8'?>
<feed xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:arxiv="http://arxiv.org/schemas/atom" xmlns="http://www.w3.org/2005/Atom">
  <id>https://arxiv.org/api/WFquG1CEVlfg5AL6NF3pd5hfYDo</id>
  <title>arXiv Query: search_query=cat:cs.CV&amp;id_list=&amp;start=0&amp;max_results=2</title>
  <updated>2026-05-21T04:57:07Z</updated>
  <link href="https://arxiv.org/api/query?search_query=cat:cs.CV&amp;start=0&amp;max_results=2&amp;id_list=" type="application/atom+xml"/>
  <opensearch:itemsPerPage>2</opensearch:itemsPerPage>
  <opensearch:totalResults>193077</opensearch:totalResults>
  <opensearch:startIndex>0</opensearch:startIndex>
  <entry>
    <id>http://arxiv.org/abs/2012.11486v1</id>
    <title>Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs</title>
    <updated>2020-12-21T17:00:05Z</updated>
    <link href="https://arxiv.org/abs/2012.11486v1" rel="alternate" type="text/html"/>
    <link href="https://arxiv.org/pdf/2012.11486v1" rel="related" type="application/pdf" title="pdf"/>
    <summary>Plant phenotyping tasks such as leaf segmentation and counting are fundamental to the study of phenotypic traits. Since it is well-suited for these tasks, deep supervised learning has been prevalent in recent works proposing better performing models at segmenting and counting leaves. Despite good efforts from research groups, one of the main challenges for proposing better methods is still the limitation of labelled data availability. The main efforts of the field seem to be augmenting existing limited data sets, and some aspects of the modelling process have been under-discussed. This paper explores such topics and present experiments that led to the development of the best-performing method in the Leaf Segmentation Challenge and in another external data set of Komatsuna plants. The model has competitive performance while been arguably simpler than other recently proposed
型別：<class 'str'>

In [4]:
print(res.text)

<?xml version='1.0' encoding='UTF-8'?>
<feed xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:arxiv="http://arxiv.org/schemas/atom" xmlns="http://www.w3.org/2005/Atom">
  <id>https://arxiv.org/api/WFquG1CEVlfg5AL6NF3pd5hfYDo</id>
  <title>arXiv Query: search_query=cat:cs.CV&amp;id_list=&amp;start=0&amp;max_results=2</title>
  <updated>2026-05-21T01:42:16Z</updated>
  <link href="https://arxiv.org/api/query?search_query=cat:cs.CV&amp;start=0&amp;max_results=2&amp;id_list=" type="application/atom+xml"/>
  <opensearch:itemsPerPage>2</opensearch:itemsPerPage>
  <opensearch:totalResults>193038</opensearch:totalResults>
  <opensearch:startIndex>0</opensearch:startIndex>
  <entry>
    <id>http://arxiv.org/abs/2012.11486v1</id>
    <title>Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs</title>
    <updated>2020-12-21T17:00:05Z</updated>
    <link href="https://arxiv.org/abs/2012.11486v1" rel="alternate" type="text/html"/>
    <link href="https://arxiv.org/pdf/2012.11486v1" rel="related" type="application/pdf" title="pdf"/>
    <summary>Plant phenotyping tasks such as leaf segmentation and counting are fundamental to the study of phenotypic traits. Since it is well-suited for these tasks, deep supervised learning has been prevalent in recent works proposing better performing models at segmenting and counting leaves. Despite good efforts from research groups, one of the main challenges for proposing better methods is still the limitation of labelled data availability. The main efforts of the field seem to be augmenting existing limited data sets, and some aspects of the modelling process have been under-discussed. This paper explores such topics and present experiments that led to the development of the best-performing method in the Leaf Segmentation Challenge and in another external data set of Komatsuna plants. The model has competitive performance while been arguably simpler than other recently proposed ones. The experiments also brought insights such as the fact that model cardinality and test-time augmentation may have strong applications in object segmentation of single class and high occlusion, and regarding the data distribution of recently proposed data sets for benchmarking.</summary>
    <category term="cs.CV" scheme="http://arxiv.org/schemas/atom"/>
    <published>2020-12-21T17:00:05Z</published>
    <arxiv:primary_category term="cs.CV"/>
    <author>
      <name>Douglas Pinto Sampaio Gomes</name>
    </author>
    <author>
      <name>Lihong Zheng</name>
    </author>
  </entry>
  <entry>
    <id>http://arxiv.org/abs/2012.10066v1</id>
    <title>PointINet: Point Cloud Frame Interpolation Network</title>
    <updated>2020-12-18T06:15:01Z</updated>
    <link href="https://arxiv.org/abs/2012.10066v1" rel="alternate" type="text/html"/>
    <link href="https://arxiv.org/pdf/2012.10066v1" rel="related" type="application/pdf" title="pdf"/>
    <summary>LiDAR point cloud streams are usually sparse in time dimension, which is limited by hardware performance. Generally, the frame rates of mechanical LiDAR sensors are 10 to 20 Hz, which is much lower than other commonly used sensors like cameras. To overcome the temporal limitations of LiDAR sensors, a novel task named Point Cloud Frame Interpolation is studied in this paper. Given two consecutive point cloud frames, Point Cloud Frame Interpolation aims to generate intermediate frame(s) between them. To achieve that, we propose a novel framework, namely Point Cloud Frame Interpolation Network (PointINet). Based on the proposed method, the low frame rate point cloud streams can be upsampled to higher frame rates. We start by estimating bi-directional 3D scene flow between the two point clouds and then warp them to the given time step based on the 3D scene flow. To fuse the two warped frames and generate intermediate point cloud(s), we propose a novel learning-based points fusion module, which simultaneously takes two warped point clouds into consideration. We design both quantitative and qualitative experiments to evaluate the performance of the point cloud frame interpolation method and extensive experiments on two large scale outdoor LiDAR datasets demonstrate the effectiveness of the proposed PointINet. Our code is available at https://github.com/ispc-lab/PointINet.git.</summary>
    <category term="cs.CV" scheme="http://arxiv.org/schemas/atom"/>
    <published>2020-12-18T06:15:01Z</published>
    <arxiv:comment>Accepted to AAAI 2021</arxiv:comment>
    <arxiv:primary_category term="cs.CV"/>
    <author>
      <name>Fan Lu</name>
    </author>
    <author>
      <name>Guang Chen</name>
    </author>
    <author>
      <name>Sanqing Qu</name>
    </author>
    <author>
      <name>Zhijun Li</name>
    </author>
    <author>
      <name>Yinlong Liu</name>
    </author>
    <author>
      <name>Alois Knoll</name>
    </author>
  </entry>
</feed>

In [ ]:
"""
http://export.arxiv.org/api/query?search_query=cat:cs.CV&max_results=2 
arxiv 指定的API基本網址用法
cs.CV -> cs = Cumputer science, CV = Computer Vision

ti -> Title, au -> Author, abs -> Abstract, co -> Comment
jr -> Journal Reference, cat -> Subject Category
rn -> Report Number, id -> Id (use id_list instead)
all -> All of the above

?xml version='1.0' -> xml的版本

<feed 
    xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" 
    xmlns:arxiv="http://arxiv.org/schemas/atom" 
    xmlns="http://www.w3.org/2005/Atom"
    >

xmlns = XML Name Space
xmlns="http://www.w3.org/2005/Atom" -> 預設命名
例如: title, summary, author, id, published

xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/"
-> 有 opensearch: 都是屬於這種 
    <opensearch:itemsPerPage>2</opensearch:itemsPerPage>
    <opensearch:totalResults>192035</opensearch:totalResults>
    <opensearch:startIndex>0</opensearch:startIndex>

xmlns:arxiv="http://arxiv.org/schemas/atom" 
-> 有 arxiv: 都是arxiv 自己定義的
    <arxiv:primary_category term="cs.CV"/>

"""

In [ ]:
"""
每個 entry 都是一篇論文的資訊
<entry>
    <id>http://arxiv.org/abs/2012.11486v1</id>
    <title>Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs</title>
    <updated>2020-12-21T17:00:05Z</updated>
    <link href="https://arxiv.org/abs/2012.11486v1" rel="alternate" type="text/html"/>
    <link href="https://arxiv.org/pdf/2012.11486v1" rel="related" type="application/pdf" title="pdf"/>
    <summary>Plant phenotyping tasks such as leaf segmentation and counting are fundamental to the study of phenotypic traits. Since it is well-suited for these tasks, deep supervised learning has been prevalent in recent works proposing better performing models at segmenting and counting leaves. Despite good efforts from research groups, one of the main challenges for proposing better methods is still the limitation of labelled data availability. The main efforts of the field seem to be augmenting existing limited data sets, and some aspects of the modelling process have been under-discussed. This paper explores such topics and present experiments that led to the development of the best-performing method in the Leaf Segmentation Challenge and in another external data set of Komatsuna plants. The model has competitive performance while been arguably simpler than other recently proposed ones. The experiments also brought insights such as the fact that model cardinality and test-time augmentation may have strong applications in object segmentation of single class and high occlusion, and regarding the data distribution of recently proposed data sets for benchmarking.</summary>
    <category term="cs.CV" scheme="http://arxiv.org/schemas/atom"/>
    <published>2020-12-21T17:00:05Z</published>
    <arxiv:primary_category term="cs.CV"/>
    <author>
      <name>Douglas Pinto Sampaio Gomes</name>
    </author>
    <author>
      <name>Lihong Zheng</name>
    </author>
  </entry>
"""

In [5]:
soup = bs(res.text, "xml")
#print(soup)
print(soup.title)
print(soup.title.text)

<title>arXiv Query: search_query=cat:cs.CV&amp;id_list=&amp;start=0&amp;max_results=2</title>
arXiv Query: search_query=cat:cs.CV&id_list=&start=0&max_results=2

In [ ]:
entries = soup.find_all("entry")
for entry in entries:
    print(entry)

print(entries)
print(f"找到{len(entries)}個entries")

<entry>
<id>http://arxiv.org/abs/2012.11486v1</id>
<title>Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs</title>
<updated>2020-12-21T17:00:05Z</updated>
<link href="https://arxiv.org/abs/2012.11486v1" rel="alternate" type="text/html"/>
<link href="https://arxiv.org/pdf/2012.11486v1" rel="related" title="pdf" type="application/pdf"/>
<summary>Plant phenotyping tasks such as leaf segmentation and counting are fundamental to the study of phenotypic traits. Since it is well-suited for these tasks, deep supervised learning has been prevalent in recent works proposing better performing models at segmenting and counting leaves. Despite good efforts from research groups, one of the main challenges for proposing better methods is still the limitation of labelled data availability. The main efforts of the field seem to be augmenting existing limited data sets, and some aspects of the modelling process have been under-discussed. This paper explores such topics and present experiments that led to the development of the best-performing method in the Leaf Segmentation Challenge and in another external data set of Komatsuna plants. The model has competitive performance while been arguably simpler than other recently proposed ones. The experiments also brought insights such as the fact that model cardinality and test-time augmentation may have strong applications in object segmentation of single class and high occlusion, and regarding the data distribution of recently proposed data sets for benchmarking.</summary>
<category scheme="http://arxiv.org/schemas/atom" term="cs.CV"/>
<published>2020-12-21T17:00:05Z</published>
<arxiv:primary_category term="cs.CV"/>
<author>
<name>Douglas Pinto Sampaio Gomes</name>
</author>
<author>
<name>Lihong Zheng</name>
</author>
</entry>
<entry>
<id>http://arxiv.org/abs/2012.10066v1</id>
<title>PointINet: Point Cloud Frame Interpolation Network</title>
<updated>2020-12-18T06:15:01Z</updated>
<link href="https://arxiv.org/abs/2012.10066v1" rel="alternate" type="text/html"/>
<link href="https://arxiv.org/pdf/2012.10066v1" rel="related" title="pdf" type="application/pdf"/>
<summary>LiDAR point cloud streams are usually sparse in time dimension, which is limited by hardware performance. Generally, the frame rates of mechanical LiDAR sensors are 10 to 20 Hz, which is much lower than other commonly used sensors like cameras. To overcome the temporal limitations of LiDAR sensors, a novel task named Point Cloud Frame Interpolation is studied in this paper. Given two consecutive point cloud frames, Point Cloud Frame Interpolation aims to generate intermediate frame(s) between them. To achieve that, we propose a novel framework, namely Point Cloud Frame Interpolation Network (PointINet). Based on the proposed method, the low frame rate point cloud streams can be upsampled to higher frame rates. We start by estimating bi-directional 3D scene flow between the two point clouds and then warp them to the given time step based on the 3D scene flow. To fuse the two warped frames and generate intermediate point cloud(s), we propose a novel learning-based points fusion module, which simultaneously takes two warped point clouds into consideration. We design both quantitative and qualitative experiments to evaluate the performance of the point cloud frame interpolation method and extensive experiments on two large scale outdoor LiDAR datasets demonstrate the effectiveness of the proposed PointINet. Our code is available at https://github.com/ispc-lab/PointINet.git.</summary>
<category scheme="http://arxiv.org/schemas/atom" term="cs.CV"/>
<published>2020-12-18T06:15:01Z</published>
<arxiv:comment>Accepted to AAAI 2021</arxiv:comment>
<arxiv:primary_category term="cs.CV"/>
<author>
<name>Fan Lu</name>
</author>
<author>
<name>Guang Chen</name>
</author>
<author>
<name>Sanqing Qu</name>
</author>
<author>
<name>Zhijun Li</name>
</author>
<author>
<name>Yinlong Liu</name>
</author>
<author>
<name>Alois Knoll</name>
</author>
</entry>
[<entry>
<id>http://arxiv.org/abs/2012.11486v1</id>
<title>Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs</title>
<updated>2020-12-21T17:00:05Z</updated>
<link href="https://arxiv.org/abs/2012.11486v1" rel="alternate" type="text/html"/>
<link href="https://arxiv.org/pdf/2012.11486v1" rel="related" title="pdf" type="application/pdf"/>
<summary>Plant phenotyping tasks such as leaf segmentation and counting are fundamental to the study of phenotypic traits. Since it is well-suited for these tasks, deep supervised learning has been prevalent in recent works proposing better performing models at segmenting and counting leaves. Despite good efforts from research groups, one of the main challenges for proposing better methods is still the limitation of labelled data availability. The main efforts of the field seem to be augmenting existing limited data sets, and some aspects of the modelling process have been under-discussed. This paper explores such topics and present experiments that led to the development of the best-performing method in the Leaf Segmentation Challenge and in another external data set of Komatsuna plants. The model has competitive performance while been arguably simpler than other recently proposed ones. The experiments also brought insights such as the fact that model cardinality and test-time augmentation may have strong applications in object segmentation of single class and high occlusion, and regarding the data distribution of recently proposed data sets for benchmarking.</summary>
<category scheme="http://arxiv.org/schemas/atom" term="cs.CV"/>
<published>2020-12-21T17:00:05Z</published>
<arxiv:primary_category term="cs.CV"/>
<author>
<name>Douglas Pinto Sampaio Gomes</name>
</author>
<author>
<name>Lihong Zheng</name>
</author>
</entry>, <entry>
<id>http://arxiv.org/abs/2012.10066v1</id>
<title>PointINet: Point Cloud Frame Interpolation Network</title>
<updated>2020-12-18T06:15:01Z</updated>
<link href="https://arxiv.org/abs/2012.10066v1" rel="alternate" type="text/html"/>
<link href="https://arxiv.org/pdf/2012.10066v1" rel="related" title="pdf" type="application/pdf"/>
<summary>LiDAR point cloud streams are usually sparse in time dimension, which is limited by hardware performance. Generally, the frame rates of mechanical LiDAR sensors are 10 to 20 Hz, which is much lower than other commonly used sensors like cameras. To overcome the temporal limitations of LiDAR sensors, a novel task named Point Cloud Frame Interpolation is studied in this paper. Given two consecutive point cloud frames, Point Cloud Frame Interpolation aims to generate intermediate frame(s) between them. To achieve that, we propose a novel framework, namely Point Cloud Frame Interpolation Network (PointINet). Based on the proposed method, the low frame rate point cloud streams can be upsampled to higher frame rates. We start by estimating bi-directional 3D scene flow between the two point clouds and then warp them to the given time step based on the 3D scene flow. To fuse the two warped frames and generate intermediate point cloud(s), we propose a novel learning-based points fusion module, which simultaneously takes two warped point clouds into consideration. We design both quantitative and qualitative experiments to evaluate the performance of the point cloud frame interpolation method and extensive experiments on two large scale outdoor LiDAR datasets demonstrate the effectiveness of the proposed PointINet. Our code is available at https://github.com/ispc-lab/PointINet.git.</summary>
<category scheme="http://arxiv.org/schemas/atom" term="cs.CV"/>
<published>2020-12-18T06:15:01Z</published>
<arxiv:comment>Accepted to AAAI 2021</arxiv:comment>
<arxiv:primary_category term="cs.CV"/>
<author>
<name>Fan Lu</name>
</author>
<author>
<name>Guang Chen</name>
</author>
<author>
<name>Sanqing Qu</name>
</author>
<author>
<name>Zhijun Li</name>
</author>
<author>
<name>Yinlong Liu</name>
</author>
<author>
<name>Alois Knoll</name>
</author>
</entry>]
找到2個entries

In [37]:
# title
entry_1 = entries[0]
print(entry_1)
print("--"*50)

entry_1_title = entry_1.find("title").text
print(repr(entry_1_title))
# 去除前後空白和換行
entry_1_title_strip = entry_1_title.strip()
print(entry_1_title_strip)

<entry>
<id>http://arxiv.org/abs/2012.11486v1</id>
<title>Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs</title>
<updated>2020-12-21T17:00:05Z</updated>
<link href="https://arxiv.org/abs/2012.11486v1" rel="alternate" type="text/html"/>
<link href="https://arxiv.org/pdf/2012.11486v1" rel="related" title="pdf" type="application/pdf"/>
<summary>Plant phenotyping tasks such as leaf segmentation and counting are fundamental to the study of phenotypic traits. Since it is well-suited for these tasks, deep supervised learning has been prevalent in recent works proposing better performing models at segmenting and counting leaves. Despite good efforts from research groups, one of the main challenges for proposing better methods is still the limitation of labelled data availability. The main efforts of the field seem to be augmenting existing limited data sets, and some aspects of the modelling process have been under-discussed. This paper explores such topics and present experiments that led to the development of the best-performing method in the Leaf Segmentation Challenge and in another external data set of Komatsuna plants. The model has competitive performance while been arguably simpler than other recently proposed ones. The experiments also brought insights such as the fact that model cardinality and test-time augmentation may have strong applications in object segmentation of single class and high occlusion, and regarding the data distribution of recently proposed data sets for benchmarking.</summary>
<category scheme="http://arxiv.org/schemas/atom" term="cs.CV"/>
<published>2020-12-21T17:00:05Z</published>
<arxiv:primary_category term="cs.CV"/>
<author>
<name>Douglas Pinto Sampaio Gomes</name>
</author>
<author>
<name>Lihong Zheng</name>
</author>
</entry>
----------------------------------------------------------------------------------------------------
'Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs'
Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs

In [8]:
# summary

summary = entry_1.find("summary").text.strip()

print(summary)

Plant phenotyping tasks such as leaf segmentation and counting are fundamental to the study of phenotypic traits. Since it is well-suited for these tasks, deep supervised learning has been prevalent in recent works proposing better performing models at segmenting and counting leaves. Despite good efforts from research groups, one of the main challenges for proposing better methods is still the limitation of labelled data availability. The main efforts of the field seem to be augmenting existing limited data sets, and some aspects of the modelling process have been under-discussed. This paper explores such topics and present experiments that led to the development of the best-performing method in the Leaf Segmentation Challenge and in another external data set of Komatsuna plants. The model has competitive performance while been arguably simpler than other recently proposed ones. The experiments also brought insights such as the fact that model cardinality and test-time augmentation may have strong applications in object segmentation of single class and high occlusion, and regarding the data distribution of recently proposed data sets for benchmarking.

In [9]:
# date
published = entry_1.find("published").text
print(f"原本的日期:{published}")
published_main = published[:10]
print(f"需要的日期:{published_main}")

原本的日期:2020-12-21T17:00:05Z
需要的日期:2020-12-21

In [10]:
# 作者(通常多個)
authors = entry_1.find_all("author")
print(f"總共有{len(authors)}個作者")

authors_list = []
for a in authors:
    author_name = a.find("name")
    authors_list.append(author_name.text)

print(authors_list)
print(f"論文作者列:{authors_list}")

總共有2個作者
['Douglas Pinto Sampaio Gomes', 'Lihong Zheng']
論文作者列:['Douglas Pinto Sampaio Gomes', 'Lihong Zheng']

In [11]:
# 論文的網址,id
link = entry_1.find("id").text
print(f"論文連結：{link}")

論文連結：http://arxiv.org/abs/2012.11486v1

In [12]:
# 整理
paper = {
    "論文名" : entry_1_title_strip,
    "摘要" : summary,
    "發表時間" : published_main,
    "作者" : authors_list,
    "論文網址" : link
}
for key, value in paper.items():
    print(f"\n{key}")
    print(value)

論文名
Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs

摘要
Plant phenotyping tasks such as leaf segmentation and counting are fundamental to the study of phenotypic traits. Since it is well-suited for these tasks, deep supervised learning has been prevalent in recent works proposing better performing models at segmenting and counting leaves. Despite good efforts from research groups, one of the main challenges for proposing better methods is still the limitation of labelled data availability. The main efforts of the field seem to be augmenting existing limited data sets, and some aspects of the modelling process have been under-discussed. This paper explores such topics and present experiments that led to the development of the best-performing method in the Leaf Segmentation Challenge and in another external data set of Komatsuna plants. The model has competitive performance while been arguably simpler than other recently proposed ones. The experiments also brought insights such as the fact that model cardinality and test-time augmentation may have strong applications in object segmentation of single class and high occlusion, and regarding the data distribution of recently proposed data sets for benchmarking.

發表時間
2020-12-21

作者
['Douglas Pinto Sampaio Gomes', 'Lihong Zheng']

論文網址
http://arxiv.org/abs/2012.11486v1

In [ ]:
# 錯誤的 全部整理
papers = []
for entry in entries:
    paper = {
        "論文名" : entry_1_title_strip,
        "摘要" : summary,
        "發表時間" : published_main,
        "作者" : authors_list,
        "論文網址" : link
    }
    papers.append(paper)

print(f"總共{len(papers)}篇論文")
print(f"第一篇論文名:{papers[0]['論文名']}")
print(f"第一篇論文名:{papers[0]['作者']}")
print(f"第二篇論文名:{papers[1]['論文名']}")
print(f"第二篇論文名:{papers[1]['作者']}")

# 錯誤

總共2篇論文
第一篇論文名:Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs
第一篇論文名:['Douglas Pinto Sampaio Gomes', 'Lihong Zheng']
第二篇論文名:Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs
第二篇論文名:['Douglas Pinto Sampaio Gomes', 'Lihong Zheng']

In [ ]:
papers = []   

for entry in entries:
    authors_list = []
    for a in entry.find_all("author"):
        authors_list.append(a.find("name").text)

    paper = {
        "論文名" : entry.find("title").text.strip(),
        "摘要" : entry.find("summary").text.strip(),
        "發表時間" : entry.find("published").text[:10],
        "作者" : authors_list,
        "論文網址" : entry.find("id").text
    }
    papers.append(paper)

print(f"總共{len(papers)}篇論文")
print(f"第一篇論文名:{papers[0]['論文名']}")
print(f"第一篇論文摘要:{papers[0]['摘要']}")
print(f"第一篇論文發表時間:{papers[0]['發表時間']}")
print(f"第一篇論文作者:{papers[0]['作者']}")
print(f"第一篇論文網址:{papers[0]['論文網址']}")
print("--"*30)
print(f"第二篇論文名:{papers[1]['論文名']}")
print(f"第二篇論文摘要:{papers[1]['摘要']}")
print(f"第二篇論文發表時間:{papers[1]['發表時間']}")
print(f"第二篇論文作者:{papers[1]['作者']}")
print(f"第二篇論文網址:{papers[1]['論文網址']}")

總共2篇論文
第一篇論文名:Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs
第一篇論文摘要:Plant phenotyping tasks such as leaf segmentation and counting are fundamental to the study of phenotypic traits. Since it is well-suited for these tasks, deep supervised learning has been prevalent in recent works proposing better performing models at segmenting and counting leaves. Despite good efforts from research groups, one of the main challenges for proposing better methods is still the limitation of labelled data availability. The main efforts of the field seem to be augmenting existing limited data sets, and some aspects of the modelling process have been under-discussed. This paper explores such topics and present experiments that led to the development of the best-performing method in the Leaf Segmentation Challenge and in another external data set of Komatsuna plants. The model has competitive performance while been arguably simpler than other recently proposed ones. The experiments also brought insights such as the fact that model cardinality and test-time augmentation may have strong applications in object segmentation of single class and high occlusion, and regarding the data distribution of recently proposed data sets for benchmarking.
第一篇論文發表時間:2020-12-21
第一篇論文作者:['Douglas Pinto Sampaio Gomes', 'Lihong Zheng']
第一篇論文網址:http://arxiv.org/abs/2012.11486v1
------------------------------------------------------------
第二篇論文名:PointINet: Point Cloud Frame Interpolation Network
第二篇論文摘要:LiDAR point cloud streams are usually sparse in time dimension, which is limited by hardware performance. Generally, the frame rates of mechanical LiDAR sensors are 10 to 20 Hz, which is much lower than other commonly used sensors like cameras. To overcome the temporal limitations of LiDAR sensors, a novel task named Point Cloud Frame Interpolation is studied in this paper. Given two consecutive point cloud frames, Point Cloud Frame Interpolation aims to generate intermediate frame(s) between them. To achieve that, we propose a novel framework, namely Point Cloud Frame Interpolation Network (PointINet). Based on the proposed method, the low frame rate point cloud streams can be upsampled to higher frame rates. We start by estimating bi-directional 3D scene flow between the two point clouds and then warp them to the given time step based on the 3D scene flow. To fuse the two warped frames and generate intermediate point cloud(s), we propose a novel learning-based points fusion module, which simultaneously takes two warped point clouds into consideration. We design both quantitative and qualitative experiments to evaluate the performance of the point cloud frame interpolation method and extensive experiments on two large scale outdoor LiDAR datasets demonstrate the effectiveness of the proposed PointINet. Our code is available at https://github.com/ispc-lab/PointINet.git.
第二篇論文發表時間:2020-12-18
第二篇論文作者:['Fan Lu', 'Guang Chen', 'Sanqing Qu', 'Zhijun Li', 'Yinlong Liu', 'Alois Knoll']
第二篇論文網址:http://arxiv.org/abs/2012.10066v1

In [15]:
# dataframe

df = pd.DataFrame(papers)
df

,論文名,摘要,發表時間,作者,論文網址
0,Leaf Segmentation and Counting with Deep Learn...,Plant phenotyping tasks such as leaf segmentat...,2020-12-21,"[Douglas Pinto Sampaio Gomes, Lihong Zheng]",http://arxiv.org/abs/2012.11486v1
1,PointINet: Point Cloud Frame Interpolation Net...,LiDAR point cloud streams are usually sparse i...,2020-12-18,"[Fan Lu, Guang Chen, Sanqing Qu, Zhijun Li, Yi...",http://arxiv.org/abs/2012.10066v1

In [ ]:
for i, paper in enumerate(papers): # tuple
    print(f"第 {i+1} 篇")
    print(f"標題：{paper['論文名']}")
    print(f"摘要：{paper['摘要']}")
    print(f"發表時間：{paper['發表時間']}")
    print(f"作者：{paper['作者']}")
    print(f"論文網址：{paper['論文網址']}")
    print("--"*30)

第 1 篇
標題：Leaf Segmentation and Counting with Deep Learning: on Model Certainty, Test-Time Augmentation, Trade-Offs
摘要：Plant phenotyping tasks such as leaf segmentation and counting are fundamental to the study of phenotypic traits. Since it is well-suited for these tasks, deep supervised learning has been prevalent in recent works proposing better performing models at segmenting and counting leaves. Despite good efforts from research groups, one of the main challenges for proposing better methods is still the limitation of labelled data availability. The main efforts of the field seem to be augmenting existing limited data sets, and some aspects of the modelling process have been under-discussed. This paper explores such topics and present experiments that led to the development of the best-performing method in the Leaf Segmentation Challenge and in another external data set of Komatsuna plants. The model has competitive performance while been arguably simpler than other recently proposed ones. The experiments also brought insights such as the fact that model cardinality and test-time augmentation may have strong applications in object segmentation of single class and high occlusion, and regarding the data distribution of recently proposed data sets for benchmarking.
發表時間：2020-12-21
作者：['Douglas Pinto Sampaio Gomes', 'Lihong Zheng']
論文網址：http://arxiv.org/abs/2012.11486v1
------------------------------------------------------------
第 2 篇
標題：PointINet: Point Cloud Frame Interpolation Network
摘要：LiDAR point cloud streams are usually sparse in time dimension, which is limited by hardware performance. Generally, the frame rates of mechanical LiDAR sensors are 10 to 20 Hz, which is much lower than other commonly used sensors like cameras. To overcome the temporal limitations of LiDAR sensors, a novel task named Point Cloud Frame Interpolation is studied in this paper. Given two consecutive point cloud frames, Point Cloud Frame Interpolation aims to generate intermediate frame(s) between them. To achieve that, we propose a novel framework, namely Point Cloud Frame Interpolation Network (PointINet). Based on the proposed method, the low frame rate point cloud streams can be upsampled to higher frame rates. We start by estimating bi-directional 3D scene flow between the two point clouds and then warp them to the given time step based on the 3D scene flow. To fuse the two warped frames and generate intermediate point cloud(s), we propose a novel learning-based points fusion module, which simultaneously takes two warped point clouds into consideration. We design both quantitative and qualitative experiments to evaluate the performance of the point cloud frame interpolation method and extensive experiments on two large scale outdoor LiDAR datasets demonstrate the effectiveness of the proposed PointINet. Our code is available at https://github.com/ispc-lab/PointINet.git.
發表時間：2020-12-18
作者：['Fan Lu', 'Guang Chen', 'Sanqing Qu', 'Zhijun Li', 'Yinlong Liu', 'Alois Knoll']
論文網址：http://arxiv.org/abs/2012.10066v1
------------------------------------------------------------

In [17]:
df.to_csv('cv_papers_results=2.csv', index=False, encoding='utf-8-sig')
print(f"儲存共 {len(papers)} 筆論文 → cv_papers_results.csv")

儲存共 2 筆論文 → cv_papers_results.csv

In [1]:
%pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\jolin\Desktop\husband\AIPE\Midterm_projuct\.venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\jolin\Desktop\husband\AIPE\Midterm_projuct\.venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\jolin\Desktop\husband\AIPE\Midterm_projuct\.venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\jolin\Desktop\husband\AIPE\Midterm_projuct\.venv\Lib\site-packages)

In [23]:
%pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [18]:
import pymysql
from configparser import ConfigParser

In [19]:
# 連到mysql
config = ConfigParser()
config.read("config.ini", encoding="utf-8")

connection = pymysql.connect(
    host = config.get('DB', 'host'),
    user = config.get('DB', 'user'),
    password = config.get('DB', 'password'),
    port = config.getint('DB', 'port'),
    charset = "utf8mb4",
    cursorclass = pymysql.cursors.DictCursor
)

In [ ]:
# 建立 database
with connection.cursor() as cursor :
    sql = """
        CREATE DATABASE IF NOT EXISTS arxiv_db
    """

    cursor.execute(sql)
    
print(f"建立arxiv_db")

建立arxiv_db

In [21]:
# 因為建立 arxiv_db
# 所以重新連線 並 指定 database
config = ConfigParser()
config.read("config.ini", encoding="utf-8")

connection = pymysql.connect(
    host = config.get('DB', 'host'),
    user = config.get('DB', 'user'),
    password = config.get('DB', 'password'),
    port = config.getint('DB', 'port'),
    database = 'arxiv_db',
    charset = "utf8mb4",
    cursorclass = pymysql.cursors.DictCursor
)

In [22]:
# 建立 主table

with connection.cursor() as cursor :
    sql = """
        CREATE TABLE IF NOT EXISTS papers(
        id  INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(500),
        summary TEXT,
        published DATE,
        link VARCHAR(500) UNIQUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """
    cursor.execute(sql)
    cursor.execute("DESC papers")
    result = cursor.fetchall()
    for row in result:
        print(row)
        
print(f"建立table papers")

{'Field': 'id', 'Type': 'int', 'Null': 'NO', 'Key': 'PRI', 'Default': None, 'Extra': 'auto_increment'}
{'Field': 'title', 'Type': 'varchar(500)', 'Null': 'YES', 'Key': '', 'Default': None, 'Extra': ''}
{'Field': 'summary', 'Type': 'text', 'Null': 'YES', 'Key': '', 'Default': None, 'Extra': ''}
{'Field': 'published', 'Type': 'date', 'Null': 'YES', 'Key': '', 'Default': None, 'Extra': ''}
{'Field': 'link', 'Type': 'varchar(500)', 'Null': 'YES', 'Key': 'UNI', 'Default': None, 'Extra': ''}
{'Field': 'created_at', 'Type': 'timestamp', 'Null': 'YES', 'Key': '', 'Default': 'CURRENT_TIMESTAMP', 'Extra': 'DEFAULT_GENERATED'}
建立table papers

In [23]:
# 因為一篇論文通常作者有好幾個
# 所以建一個 作者表

with connection.cursor() as cursor :
    sql = """
        CREATE TABLE IF NOT EXISTS authors(
            id INT AUTO_INCREMENT PRIMARY KEY,
            paper_id INT,
            name VARCHAR(255),
            FOREIGN KEY (paper_id) REFERENCES papers(id)
        )
    """
    cursor.execute(sql)
    cursor.execute("DESC authors")
    result = cursor.fetchall()
    for row in result:
        print(row)
    

print(f"建立table authers")

{'Field': 'id', 'Type': 'int', 'Null': 'NO', 'Key': 'PRI', 'Default': None, 'Extra': 'auto_increment'}
{'Field': 'paper_id', 'Type': 'int', 'Null': 'YES', 'Key': 'MUL', 'Default': None, 'Extra': ''}
{'Field': 'name', 'Type': 'varchar(255)', 'Null': 'YES', 'Key': '', 'Default': None, 'Extra': ''}
建立table authers

In [24]:
# 紀錄 爬取的紀錄表 search_logs

with connection.cursor() as cursor :
    sql = """
        CREATE TABLE IF NOT EXISTS search_logs(
            id INT AUTO_INCREMENT PRIMARY KEY,
            query VARCHAR(255),
            result_count INT,
            search_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """
    cursor.execute(sql)

print(f"建立search_logs")

建立search_logs

In [25]:
# 寫入 papers 和 authors

new_count = 0 
# 成功新增的

duplicate_count = 0 
# 被阻止寫入的重複筆數

with connection.cursor() as cursor :
    for paper in papers:
        try:
            sql = """
                INSERT INTO papers(title, summary, published, link)
                VALUES (%s, %s, %s, %s)
            """
            cursor.execute(sql, (
                paper["論文名"],
                paper["摘要"],
                paper["發表時間"],
                paper["論文網址"]
            ))

            paper_id = cursor.lastrowid

            sql = """
                    INSERT INTO authors(paper_id, name)
                    VALUES (%s, %s)
                """

            for author in paper["作者"]:
                cursor.execute(sql, (paper_id, author))
            
            new_count += 1
        
        except pymysql.err.IntegrityError:
            duplicate_count += 1
    
    sql = """
        INSERT INTO search_logs (query, result_count)
        VALUES (%s, %s)
    """

    cursor.execute(sql, ("cat:cs.CV", new_count))

connection.commit()
print(f"新增 {new_count} 筆, 略過 {duplicate_count} 筆")

新增 2 筆, 略過 0 筆

In [26]:
# 查詢
# 查詢論文

with connection.cursor() as cursor:
    sql = """
        SELECT id, title, published
        FROM papers
        ORDER BY published DESC
    """
    # published DESC 看最新的

    cursor.execute(sql)
    results = cursor.fetchall() # 取出

df_db = pd.DataFrame(results)
print(f"資料庫有 {len(df_db)} 篇論文")
df_db

資料庫有 2 篇論文

   id                                              title   published
0   1  Leaf Segmentation and Counting with Deep Learn...  2020-12-21
1   2  PointINet: Point Cloud Frame Interpolation Net...  2020-12-18

In [27]:
# 查詢某篇論文的所有作者

with connection.cursor() as cursor:
    sql = """
        SELECT p.title, a.name
        FROM papers p
        JOIN authors a
        ON p.id = a.paper_id
        ORDER BY p.id
    """

    cursor.execute(sql)
    results = cursor.fetchall()

df_authors = pd.DataFrame(results)
df_authors

# 之後也可以針對哪個作者去做查詢或統計論文發表數量
# 或是每年的領域做論文數量統計

,title,name
0,Leaf Segmentation and Counting with Deep Learn...,Douglas Pinto Sampaio Gomes
1,Leaf Segmentation and Counting with Deep Learn...,Lihong Zheng
2,PointINet: Point Cloud Frame Interpolation Net...,Fan Lu
3,PointINet: Point Cloud Frame Interpolation Net...,Guang Chen
4,PointINet: Point Cloud Frame Interpolation Net...,Sanqing Qu
5,PointINet: Point Cloud Frame Interpolation Net...,Zhijun Li
6,PointINet: Point Cloud Frame Interpolation Net...,Yinlong Liu
7,PointINet: Point Cloud Frame Interpolation Net...,Alois Knoll

In [28]:
# 確認紀錄表
with connection.cursor() as cursor:
    sql = """
        SELECT query, result_count, search_at
        FROM search_logs
        ORDER BY search_at DESC
    """

    cursor.execute(sql)
    results = cursor.fetchall()

df_logs = pd.DataFrame(results)
df_logs

       query  result_count           search_at
0  cat:cs.CV             2 2026-05-21 10:03:03

In [29]:
# 用關鍵字找論文

keyword = "recognition"

with connection.cursor() as cursor:
    sql = """
        SELECT title, published, link
        FROM papers
        WHERE title LIKE %s OR summary LIKE %s
        ORDER BY published DESC
    """
    cursor.execute(sql, (f"%{keyword}%", f"{keyword}"))
    results = cursor.fetchall()

df_keyword = pd.DataFrame(results)
print(f"找到 {len(df_keyword)} 篇包含 {keyword} 的論文")
df_keyword

找到 0 篇包含 recognition 的論文

Empty DataFrame
Columns: []
Index: []

In [30]:
connection.close()

---
## 物件導向版本（完成版）

把前面所有步驟封裝成一個 `Arxiv` 類別：搜尋 → 整理 → 存 CSV / MySQL → 查詢。

In [ ]:
# ============================================================
# 物件導向版 arXiv 爬蟲（完成版）
# ============================================================
import requests
import pandas as pd
import pymysql
from bs4 import BeautifulSoup as bs
from configparser import ConfigParser


class Arxiv:
    """arXiv 論文爬蟲：搜尋 → 整理 → 存 CSV / MySQL → 查詢"""

    def __init__(self, max_results=20):
        self.url = "http://export.arxiv.org/api/query"
        self.max_results = max_results
        self.papers = []
        self.query = ""
        self.db = None          # 先給預設值，沒連線就呼叫也不會 AttributeError

    # ---------------- 爬取 ----------------
    def search(self, query):
        self.query = query
        params = {
            'search_query': query,
            'start': 0,
            'max_results': self.max_results,
            'sortBy': 'submittedDate',
            'sortOrder': 'descending'
        }

        res = requests.get(self.url, params=params)

        if res.status_code != 200:
            print(f"狀態碼： {res.status_code}")
            return

        self.papers = self._parse(res.text)
        print(f"取得 {len(self.papers)} 篇論文")

    def _parse(self, xml_text):
        soup = bs(xml_text, "xml")
        entries = soup.find_all("entry")

        papers = []
        for entry in entries:
            authors_list = [a.find("name").text for a in entry.find_all("author")]

            papers.append({
                "論文名": entry.find("title").text.strip(),
                "摘要": entry.find("summary").text.strip(),
                "發表時間": entry.find("published").text[:10],
                "作者": authors_list,
                "論文網址": entry.find("id").text
            })

        return papers

    # ---------------- 呈現 / 匯出 ----------------
    def paper_dataFrame(self):
        if not self.papers:
            print("沒有資料")
            return
        return pd.DataFrame(self.papers)

    def show_paper(self, index=0):
        if not self.papers:
            print("沒有資料")
            return

        paper = self.papers[index]
        print(f"論文標題 : {paper['論文名']}")
        print(f"發表時間 : {paper['發表時間']}")
        print(f"作者     : {', '.join(paper['作者'])}")
        print(f"論文摘要 : {paper['摘要']}")
        print(f"論文網址 : {paper['論文網址']}")

    def save_csv(self, filename="cs_papers.csv"):
        if not self.papers:
            print("沒有資料")
            return

        pd.DataFrame(self.papers).to_csv(filename, index=False, encoding="utf-8-sig")
        print(f"儲存了 {len(self.papers)} 筆論文到 {filename}")

    # ---------------- 資料庫 ----------------
    def connect_db(self, config_file="config.ini", database="arxiv_db"):
        config = ConfigParser()
        config.read(config_file, encoding="utf-8")

        self.db = pymysql.connect(
            host=config.get('DB', 'host'),
            user=config.get('DB', 'user'),
            password=config.get('DB', 'password'),
            port=config.getint('DB', 'port'),
            charset="utf8mb4",
            cursorclass=pymysql.cursors.DictCursor
        )

        with self.db.cursor() as cursor:
            cursor.execute(f"CREATE DATABASE IF NOT EXISTS {database}")
            cursor.execute(f"USE {database}")

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS papers(
                    id         INT AUTO_INCREMENT PRIMARY KEY,
                    title      VARCHAR(500),
                    summary    TEXT,
                    published  DATE,
                    link       VARCHAR(500) UNIQUE,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS authors(
                    id       INT AUTO_INCREMENT PRIMARY KEY,
                    paper_id INT,
                    name     VARCHAR(255),
                    FOREIGN KEY (paper_id) REFERENCES papers(id)
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS search_logs(
                    id           INT AUTO_INCREMENT PRIMARY KEY,
                    query        VARCHAR(255),
                    result_count INT,
                    searched_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            """)

        self.db.commit()
        print("資料庫已連線，papers / authors / search_logs 三張表建立完成")

    def save_db(self):
        if not self.papers:
            print("沒有資料")
            return
        if not self.db:
            print("沒有連線到資料庫，請先呼叫 connect_db()")
            return

        new_count = 0
        dup_count = 0

        with self.db.cursor() as cursor:
            for paper in self.papers:
                try:
                    cursor.execute("""
                        INSERT INTO papers(title, summary, published, link)
                        VALUES (%s, %s, %s, %s)
                    """, (
                        paper["論文名"],
                        paper["摘要"],
                        paper["發表時間"],
                        paper["論文網址"]
                    ))

                    paper_id = cursor.lastrowid

                    for author in paper["作者"]:
                        cursor.execute("""
                            INSERT INTO authors(paper_id, name)
                            VALUES (%s, %s)
                        """, (paper_id, author))

                    new_count += 1

                except pymysql.err.IntegrityError:
                    dup_count += 1

            cursor.execute("""
                INSERT INTO search_logs (query, result_count)
                VALUES (%s, %s)
            """, (self.query, new_count))

        self.db.commit()
        print(f"新增 {new_count} 筆，略過重複 {dup_count} 筆")

    # ---------------- 查詢 ----------------
    def query_papers(self, keyword=None):
        if not self.db:
            print("沒有連線到資料庫，請先呼叫 connect_db()")
            return

        with self.db.cursor() as cursor:
            if keyword:
                cursor.execute("""
                    SELECT id, title, published, link
                    FROM papers
                    WHERE title LIKE %s OR summary LIKE %s
                    ORDER BY published DESC
                """, (f"%{keyword}%", f"%{keyword}%"))
            else:
                cursor.execute("""
                    SELECT id, title, published, link
                    FROM papers
                    ORDER BY published DESC
                """)
            results = cursor.fetchall()

        print(f"查到 {len(results)} 筆論文")
        return pd.DataFrame(results)

    def query_authors(self, paper_id):
        if not self.db:
            print("沒有連線到資料庫，請先呼叫 connect_db()")
            return

        with self.db.cursor() as cursor:
            cursor.execute("""
                SELECT p.title AS 論文名, a.name AS 作者
                FROM papers p
                JOIN authors a ON p.id = a.paper_id
                WHERE p.id = %s
            """, (paper_id,))
            results = cursor.fetchall()

        return pd.DataFrame(results)

    def show_logs(self):
        if not self.db:
            print("沒有連線到資料庫，請先呼叫 connect_db()")
            return

        with self.db.cursor() as cursor:
            cursor.execute("""
                SELECT query, result_count, searched_at
                FROM search_logs
                ORDER BY searched_at DESC
            """)
            results = cursor.fetchall()

        df = pd.DataFrame(results)
        print(f"總共有 {len(df)} 筆爬取紀錄")
        return df

    def close_db(self):
        if self.db:
            self.db.close()
            self.db = None
            print("資料庫連線已關閉")
        else:
            print("目前沒有開啟中的連線")

---
## 使用示範

In [ ]:
# ▶ 建立爬蟲物件並搜尋
crawler = Arxiv(max_results=10)
crawler.search("cat:cs.CV")

In [ ]:
# ▶ 看成表格
crawler.paper_dataFrame()

In [ ]:
# ▶ 看第一篇的詳細內容
crawler.show_paper(0)

In [ ]:
# ▶ 存成 CSV
crawler.save_csv("cv_papers.csv")

In [ ]:
# ▶ 連線資料庫並建表（帳密從 config.ini 讀）
crawler.connect_db()

In [ ]:
# ▶ 把這次搜尋的結果存進資料庫
crawler.save_db()

In [ ]:
# ▶ 換一個關鍵字再搜一次，資料會繼續累積
crawler.search("cat:cs.CL")
crawler.save_db()

In [ ]:
# ▶ 從資料庫查所有論文
crawler.query_papers()

In [ ]:
# ▶ 用關鍵字查論文
crawler.query_papers("recognition")

In [ ]:
# ▶ 查某篇論文的所有作者（把 1 換成上面查到的 id）
crawler.query_authors(1)

In [ ]:
# ▶ 查看爬取紀錄
crawler.show_logs()

In [ ]:
# ▶ 關閉連線
crawler.close_db()